### ISSUE TITLE
EOFError throw by line 489 of DICOM.jl

### ISSUE THREAD

**Issue by ygidtu** [JuliaHealth/DICOM.jl#69]
![image](https://user-images.githubusercontent.com/29178828/100405393-745ab600-309e-11eb-917a-d91fdda50df3.png)

- Data source: This file is the [open source CQ500 data](http://headctstudy.qure.ai/dataset).

- Testing with [pydicom](https://pydicom.github.io/pydicom/stable/auto_examples/input_output/plot_read_dicom.html) works fine

- Testing with add try-catch around line 489, then everything seems good
    ```julia
    try
        push!(data, read!(st, Array{dtype}(undef, xr)))
    catch e
        @show e
    end
    ```
    ![image](https://user-images.githubusercontent.com/29178828/100405734-2db98b80-309f-11eb-887f-f6b7b1c2d7f6.png)

**Comment by notZaki** [comment]
It might be because the DICOM images are compressed. 
This can be checked by looking at the TransferSyntaxUID (0x0002, 0x0010) of the file.

If the images are compressed, then unfortunately this package can not read them currently.
One workaround is to decompress the images first, and then read them, as mentioned in https://github.com/JuliaHealth/DICOM.jl/issues/33#issuecomment-512952566.

**Comment by ygidtu** [comment]
I check the dcm file, as you said, it's compressed
